<!DOCTYPE html>
<html>
<head>
	<title>Wellcome</title>
	  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 45%;
      margin: auto;
  }
  </style>
</head>
<body>
<div class="container" style="margin-top: 30px">
      <div class="row">
        <div class="col-md-4">
          <h2><a href="/politic">Politics</a></h2>
          <p>
                <?php foreach ($politics as $politic) : ?>
                <?php echo '<li>'; ?>
                <?=$politic->getTitle()?>
                <?php endforeach; ?>
                <?php echo '</li>'; ?>
          </p>
          <ul></ul>
          <p><a class="btn btn-default" href="/index.php?route=news/politic" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2><a href="/sport">Sports</a></h2>
          <p>
                <?php foreach ($sports as $sport) : ?>
                <?php echo '<li>'; ?>
                <?=$sport->getTitle()?>
                <?php endforeach; ?>
                <?php echo '</li>'; ?>
           </p>
          <p><a class="btn btn-default" href="/index.php?route=news/sport" role="button">View details »</a></p>
       </div>
        <div class="col-md-4">
          <h2><a href="/science">Science</a></h2>
          <p>
        				<?php foreach ($sciences as $science) : ?>
        				<?php echo '<li>'; ?>
        				<?=$science->getTitle()?>
        				<?php endforeach; ?>
        				<?php echo '</li>'; ?>
			
          </p>
          <p><a class="btn btn-default" href="/science" role="button">View details »</a></p>
        </div>
      </div>
    </div>
   

  <div class="container">
  <hr>
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://www.sunhome.ru/i/wallpapers/128/stalker-oboi-v3.960x540.jpg" alt="Chania" width="360" height="245">
      </div>

      <div class="item">
        <img src="http://www.sunhome.ru/i/wallpapers/24/kartinki-igri-stalker.960x540.jpg" alt="Chania" width="360" height="245">
      </div>
    
      <div class="item">
        <img src="http://www.sunhome.ru/i/wallpapers/255/stalker-shadow-of-chernobyl-igra.960x540.jpg" alt="Flower" width="360" height="245">
      </div>

      <div class="item">
        <img src="http://www.sunhome.ru/i/wallpapers/208/stalker-ten-chernobilya-igra.960x540.jpg" alt="Flower" width="360" height="245">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  
  <hr>
</div>
	<footer class="footer">
      <div class="container">
        <p class="text-muted">
        <p>&copy; 2010-<?= date('Y'); ?></p> 	
      </p>
      </div>
    </footer>


</body>
</html>