<div class="container">
<h3><a href="/">Back to all news</a></h3>
<hr style="border: 1px solid gray">


<?php foreach ($politics as $politic) : ?>
		<?=$politic->getId()?> :
	    <?=$politic->getTitle()?><br>
	    <a class="btn btn-primary btn-xs" href="/politic-<?=$politic->getId()?>.html">Details</a><hr>
	     
	<?php endforeach; ?>

</div>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :
        if ($button->isActive) : ?>
            <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
        <?php else : ?>
            <li class='disabled'><a href="#"><?=$button->text?></a></li>
        <?php endif; endforeach; ?>  
      
  </ul>
</nav>
